site_name: tsca-cats
repo_url: https://github.com/patlewig/tsca-cats
site_url: https://patlewig.github.io/tsca-cats
site_description: This is a template repository for Python projects that use uv for their dependency management.
site_author: patlewig
edit_uri: edit/main/docs/
repo_name: patlewig/tsca-cats
copyright: Maintained by <a href="https://patlewig.com">patlewig</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["src/tsca_cats"]
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/patlewig/tsca-cats
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/tsca-cats

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
